name: Build PennyLane-Qrack Wheels

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch (adjust if needed)

  workflow_dispatch: # Allow manual triggering of the workflow


jobs:
  build_noble:
    runs-on: ubuntu-24.04  # Use a Noble Numbat runner
    strategy:
      matrix:
        platform:
          - manylinux_2_39_x86_64
    steps:
      - name: Checkout PennyLane-Qrack
        uses: actions/checkout@v4

      - name: Checkout Qrack
        uses: actions/checkout@v4
        with:
          repository: 'unitaryfund/qrack'
          path: qrack

      - name: Checkout Catalyst
        uses: actions/checkout@v4
        with:
          repository: 'PennyLaneAI/catalyst'
          path: catalyst

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install wheel setuptools

      - name: Prepare Build Environment (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ocl-icd-opencl-dev opencl-headers ninja-build libomp-dev

      - name: Build Qrack Linux x86-64
        run: |
          cd qrack
          mkdir build
          cd build
          cmake -DENABLE_RDRAND=OFF -DENABLE_DEVRAND=ON -DQBCAPPOW=12 -DCPP_STD=14 ..
          make qrack

      - name: Build Catalyst Linux x86-64
        run: |
          cd catalyst
          pip install -r requirements.txt
          make all

      - name: Build Wheel
        run: |
          python setup.py bdist_wheel --plat-name=${{ matrix.platform }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pennylane_qrack-${{ matrix.platform }}
          path: dist/
